---
title: "powerplant_brazil_eda"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
library(geosphere)
library(dplyr)
dat <- global_power_plant_database <- read_csv("../DATA/global_power_plant_database_v_1_3/global_power_plant_database.csv")
View(global_power_plant_database)
dat <- dat[dat$country_long == "Brazil",]
coord_df <- as.data.frame(dat[,c("gppd_idnr", "latitude", "longitude")])

pt_interest <- c(1,1)

num_factory_within_dist <- function(pt_interest, factory_coord, dist_in_m) {
  res <- get_dist_to_factory(pt_interest, factory_coord)
  filtered <- res %>% filter(dist_to_pt < dist_in_m)
  return(filtered)
}

get_dist_to_factory <- function(pt_interest, factory_coord) {
  res <- sapply(1:nrow(factory_coord), function(i) distm(factory_coord[i,c(2,3)], pt_interest, fun = distHaversine))
  factory_coord$dist_to_pt <- res
  return(factory_coord)
}

num_factory_within_dist(pt_interest, coord_df, 6509000)

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
