---
title: "Regridding"
author: "James Carzon"
date: "11/4/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(tidyverse)
require(reticulate)
require(data.table)
```

```{python}
import numpy as np
import pandas as pd
import sklearn
import scipy
import matplotlib.pyplot as plt
from global_land_mask import globe
```

```{python}
S5P_no2 = pd.read_csv("../DATA/S5P_no2.csv", index_col=0)
urbDens = pd.read_csv("../DATA/urbDens_data.csv", index_col=0)
powerPlants = pd.read_csv("../DATA/powerplants_feature.csv", index_col=0)
S5P_no2['plant_dist'] = powerPlants.min_dist_bad
S5P_no2.NO2gm[S5P_no2.NO2gm < 0] = float('NaN')
```

We regrid urban density to the NO2 data grid by linear interpolation.

```{python}
xi = np.array(S5P_no2.loc[:, ['latitude', 'longitude']])
points = np.array(urbDens.loc[:, ['latitude', 'longitude']])
values = np.array(urbDens.loc[:, 'popdens'])
regridded = scipy.interpolate.griddata(
  points=points,
  values=values,
  xi=xi,
  method='linear',
  rescale=True
)

plt.figure()
popdens_rg = plt.scatter(
  S5P_no2.longitude,
  S5P_no2.latitude,
  c=np.log(regridded),
  s=1.
)
plt.colorbar(popdens_rg)
plt.show()

```

After regridding with linear interpolation, points over the oceans within the 
convex hull of the continent's border are assigned nonzero population. We mask 
these points.

```{python}
is_land = []
for i in range(len(xi)):
  if globe.is_ocean(*xi[i]):
    regridded[i] = float('NaN')

plt.figure()
popdens_rg = plt.scatter(
  S5P_no2.longitude,
  S5P_no2.latitude,
  c=np.log(regridded),
  s=1.
)

plt.colorbar(popdens_rg)
plt.show()
```

We downsample to our domain of interest.

```{python}
S5P_no2['popdens'] = regridded
downsampled = S5P_no2[(S5P_no2.latitude <= -19) & (S5P_no2.latitude >= -24) & (S5P_no2.longitude <= -42.5) & (S5P_no2.longitude >= -47.5)]

plt.figure()
downsampled_plot = plt.scatter(
  downsampled.longitude,
  downsampled.latitude,
  c=np.log(downsampled.popdens),
  s=1.
)

plt.colorbar(downsampled_plot)
plt.show()
```

Save the fully processed data set.

```{python}
downsampled = downsampled.dropna(axis=0)
downsampled.dropna(axis=0).to_csv("../DATA/processed_data.csv")
```

